# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
#permalink:        pretty
permalink:        /blog/:title/

# Setup
title:            Catputer
tagline:          'Random musings'
description:      'A place on the internet where I pen my <s>generic</s> thoughts'
url:              http://lanyon.getpoole.com

author:
  name:           'Catputer'
  url:            http://catputer.net

paginate:         5
paginate_path:    '/blog/page:num/'

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
